version: '3.9'

services:
  dev-db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnetwork

  test-db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    networks:
      - pgnetwork

volumes:
  pgdata:

networks:
  pgnetwork:

